// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/aerosystems/auth-service/internal/config"
	"github.com/aerosystems/auth-service/internal/infrastructure/adapters/rpc"
	"github.com/aerosystems/auth-service/internal/infrastructure/repository/pg"
	"github.com/aerosystems/auth-service/internal/models"
	"github.com/aerosystems/auth-service/internal/presenters/http"
	"github.com/aerosystems/auth-service/internal/presenters/http/handlers"
	"github.com/aerosystems/auth-service/internal/usecases"
	"github.com/aerosystems/auth-service/pkg/gorm_postgres"
	"github.com/aerosystems/auth-service/pkg/logger"
	"github.com/aerosystems/auth-service/pkg/redis_client"
	"github.com/aerosystems/auth-service/pkg/rpc_client"
	"github.com/go-redis/redis/v7"
	"github.com/sirupsen/logrus"
	"gorm.io/gorm"
)

// Injectors from wire.go:

//go:generate wire
func InitApp() *App {
	logger := ProvideLogger()
	logrusLogger := ProvideLogrusLogger(logger)
	config := ProvideConfig()
	baseHandler := ProvideBaseHandler(logrusLogger, config)
	client := ProvideRedisClient(logger, config)
	tokenUsecase := ProvideTokenUsecase(client, config)
	entry := ProvideLogrusEntry(logger)
	db := ProvideGormPostgres(entry, config)
	codeRepo := ProvideCodeRepo(db, config)
	userRepo := ProvideUserRepo(db)
	checkmailAdapter := ProvideCheckmailRepo(config)
	mailAdapter := ProvideMailRepo(config)
	customerAdapter := ProvideCustomerRepo(config)
	authUsecase := ProvideAuthUsecase(codeRepo, userRepo, checkmailAdapter, mailAdapter, customerAdapter, config)
	userHandler := ProvideUserHandler(baseHandler, tokenUsecase, authUsecase)
	tokenHandler := ProvideTokenHandler(baseHandler, tokenUsecase)
	server := ProvideHttpServer(logrusLogger, config, userHandler, tokenHandler)
	app := ProvideApp(logrusLogger, config, server)
	return app
}

func ProvideApp(log *logrus.Logger, cfg *config.Config, httpServer *HttpServer.Server) *App {
	app := NewApp(log, cfg, httpServer)
	return app
}

func ProvideLogger() *logger.Logger {
	loggerLogger := logger.NewLogger()
	return loggerLogger
}

func ProvideConfig() *config.Config {
	configConfig := config.NewConfig()
	return configConfig
}

func ProvideUserHandler(baseHandler *handlers.BaseHandler, tokenUsecase handlers.TokenUsecase, authUsecase handlers.AuthUsecase) *handlers.UserHandler {
	userHandler := handlers.NewUserHandler(baseHandler, tokenUsecase, authUsecase)
	return userHandler
}

func ProvideTokenHandler(baseHandler *handlers.BaseHandler, tokenUsecase handlers.TokenUsecase) *handlers.TokenHandler {
	tokenHandler := handlers.NewTokenHandler(baseHandler, tokenUsecase)
	return tokenHandler
}

func ProvideUserRepo(db *gorm.DB) *pg.UserRepo {
	userRepo := pg.NewUserRepo(db)
	return userRepo
}

// wire.go:

func ProvideHttpServer(log *logrus.Logger, cfg *config.Config, userHandler *handlers.UserHandler, tokenHandler *handlers.TokenHandler) *HttpServer.Server {
	return HttpServer.NewServer(log, cfg.AccessSecret, userHandler, tokenHandler)
}

func ProvideLogrusEntry(log *logger.Logger) *logrus.Entry {
	return logrus.NewEntry(log.Logger)
}

func ProvideLogrusLogger(log *logger.Logger) *logrus.Logger {
	return log.Logger
}

func ProvideGormPostgres(e *logrus.Entry, cfg *config.Config) *gorm.DB {
	db := GormPostgres.NewClient(e, cfg.PostgresDSN)
	if err := db.AutoMigrate(&models.User{}, &models.Code{}); err != nil {
		panic(err)
	}
	return db
}

func ProvideRedisClient(log *logger.Logger, cfg *config.Config) *redis.Client {
	return RedisClient.NewRedisClient(log, cfg.RedisDSN, cfg.RedisPassword)
}

func ProvideBaseHandler(log *logrus.Logger, cfg *config.Config) *handlers.BaseHandler {
	return handlers.NewBaseHandler(log, cfg.Mode)
}

func ProvideAuthUsecase(codeRepo usecases.CodeRepository, userRepo usecases.UserRepository, checkmailRepo usecases.CheckmailAdapter, mailRepo usecases.MailAdapter, customerRepo usecases.CustomerAdapter, cfg *config.Config) *usecases.AuthUsecase {
	return usecases.NewAuthUsecase(codeRepo, userRepo, checkmailRepo, mailRepo, customerRepo, cfg.CodeExpMinutes)
}

func ProvideTokenUsecase(redisClient *redis.Client, cfg *config.Config) *usecases.TokenUsecase {
	return usecases.NewTokenUsecase(redisClient, cfg.AccessSecret, cfg.RefreshSecret, cfg.AccessExpMinutes, cfg.RefreshExpMinutes)
}

func ProvideCodeRepo(db *gorm.DB, cfg *config.Config) *pg.CodeRepo {
	return pg.NewCodeRepo(db, cfg.CodeExpMinutes)
}

func ProvideCheckmailRepo(cfg *config.Config) *RpcRepo.CheckmailAdapter {
	rpcClient := RpcClient.NewClient("tcp", cfg.CheckmailServiceRPCAddr)
	return RpcRepo.NewCheckmailAdapter(rpcClient)
}

func ProvideMailRepo(cfg *config.Config) *RpcRepo.MailAdapter {
	rpcClient := RpcClient.NewClient("tcp", cfg.MailServiceRPCAddr)
	return RpcRepo.NewMailAdapter(rpcClient)
}

func ProvideCustomerRepo(cfg *config.Config) *RpcRepo.CustomerAdapter {
	rpcClient := RpcClient.NewClient("tcp", cfg.CustomerServiceRPCAddr)
	return RpcRepo.NewCustomerAdapter(rpcClient)
}
